# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20160307_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
