# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20160323_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
