# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20160326_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_id',
            field=models.AutoField(default=1, primary_key=True),
            preserve_default=False,
        ),
    ]
