# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_answer_answer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
